// Generated by CoffeeScript 1.10.0
(function() {
  var BASE_URL;

  exports.xFindText = function(text) {
    return "//*[contains( normalize-space(.), '" + text + "' )]";
  };

  BASE_URL = 'http://logic-ex.butterfill.com';

  exports.BASE_URL = BASE_URL;

  exports.clearCache = function(b) {
    var error, error1, error2, error3, error4;
    b.url(BASE_URL + "/sign-in");
    try {
      b.deleteCookie();
    } catch (error1) {
      error = error1;
      console.log(error);
    }
    try {
      b.localStorage('DELETE');
    } catch (error2) {
      error = error2;
      console.log(error);
    }
    try {
      b.sessionStorage('DELETE');
    } catch (error3) {
      error = error3;
      console.log(error);
    }
    try {
      browser.click('#at-nav-button');
      return browser.waitUntil(function() {
        var res;
        res = browser.execute(function() {
          return ix.url();
        });
        return res.value === '/sign-in';
      });
    } catch (error4) {
      error = error4;
      return console.log("no sign out [may be expected]");
    }
  };

  exports.login = function(b, username, password) {
    if (username == null) {
      username = 'tester@';
    }
    if (password == null) {
      password = 'tester';
    }
    b.url(BASE_URL + "/sign-in");
    b.setValue('input[name=at-field-email]', username);
    b.setValue('input[name=at-field-password]', password);
    b.submitForm('form#at-pwd-form');
    b.waitUntil(function() {
      var res;
      res = b.execute(function() {
        return ix.url();
      });
      return res.value === '/';
    });
  };

  exports.resetTester = function(b) {
    var itExists;
    b.execute(function() {
      return FlowRouter.go('/resetTester');
    });
    b.pause(100);
    itExists = b.waitForExist('.itIsDone');
    return expect(itExists).to.be["true"];
  };

  exports.goPage = function(browser, url) {
    return browser.execute(function(url) {
      return FlowRouter.go(url);
    }, url);
  };

}).call(this);
