// Generated by CoffeeScript 1.10.0
(function() {
  describe('zoxiy', function() {
    return describe('Page title', function() {
      it('should be set by the Meteor method', function() {
        browser.url('http://localhost:3000/sign-in');
        browser.deleteCookie();
        browser.sessionStorage('DELETE');
        browser.localStorage('DELETE');
        expect(browser.getTitle()).to.equal('love-logic');
      });
    });
  });

}).call(this);
