// Generated by CoffeeScript 1.10.0
(function() {
  var base;

  base = require('./base');

  describe('zoxiy', function() {
    return describe('Page title', function() {
      it('should be set by the Meteor method', function() {
        browser.url(base.BASE_URL + "/sign-in");
        console.log("browser.getTitle() = " + (browser.getTitle()));
        expect(browser.getTitle()).to.equal('love-logic');
      });
    });
  });

}).call(this);
