// Generated by CoffeeScript 1.10.0
(function() {
  describe('zoxiy', function() {
    return describe('sign out @watch', function() {
      it('clear cache', function() {
        browser.url('http://localhost:3000/sign-in');
        browser.deleteCookie();
        browser.sessionStorage('DELETE');
        browser.localStorage('DELETE');
      });
      it('login', function() {
        var res;
        browser.url('http://localhost:3000/sign-in');
        browser.setValue('input[name=at-field-email]', 'student@');
        browser.setValue('input[name=at-field-password]', 'lovelogic');
        browser.submitForm('form#at-pwd-form');
        res = browser.execute(function() {
          return 1 + 1;
        });
        expect(res.value).to.equal(2);
        browser.waitUntil(function() {
          res = browser.execute(function() {
            return ix.url();
          });
          return res.value === '/';
        });
      });
      it('click sign out button', function() {
        browser.click('#at-nav-button');
        browser.waitUntil(function() {
          var res;
          res = browser.execute(function() {
            return ix.url();
          });
          return res.value === '/sign-in';
        });
      });
    });
  });

}).call(this);
