// Generated by CoffeeScript 1.10.0
(function() {
  var base;

  base = require('./base');

  describe('zoxiy', function() {
    return describe('student login', function() {
      it('clear cache', function() {
        return base.clearCache(browser);
      });
      return it('should be possible to login as a student', function() {
        return base.login(browser, 'student@', 'student');
      });
    });
  });

}).call(this);
